[build]
base = "/"

[build.processing]
  skip_processing = false

[[redirects]]

  from = "/login"
  to = "https://shopping-mall-api.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}